### PR TITLE
Serbian translation

### PR DESCRIPTION
**Pull request by rammba**

### CODE REVIEW

**Comment by ricardjorg** [comment]
Hi @rammba! I've added your strings to the file. It's committed, and should go live in a few minutes.
I'm closing this pull request. If you have any further changes you want to make, you can open a new pull request.
Thanks for your help! You're awesome!

**Comment by rammba** [comment]
Just a little change :)

"leaderboards-loading": "Učitavanje još timova...",
"leaderboards-loading": "Učitavanje najboljih timova...",

**Comment by ricardjorg** [comment]
@rammba it's in! Thanks!

**Comment by rammba** [comment]
@ricardjorg  I'm not able to make new pull request, can you check mine repository where I added cyrillic version and little changes to latin one :)

https://github.com/rammba/Forge2018cyrillic

**Comment by ricardjorg** [comment]
Hi @rammba. That's strange, why weren't you able to submit another request?
Did you update your local git repo before you started changing the file?
Anyway, I pushed your changes in. They're going live in a few minutes.
Thanks again!
Cheers!
Ricardo

**Comment by rammba** [comment]
For Serbian latin: 
    "leaderboards-title": "Najbolji timovi",
    "deathless-title": "Dvorana slavnih",
    "deathless-subtitle": "Timovi koji su porazili Vatrenog Svinjaklopa bez umiranja",
    "deathless-date": "Datum",
    "deathless-loading": "Učitavanje...",
    "deathless-noresults": "Nema rezultata.. Pokušajte kasnije",
    "deathless-showmore": "Prikaži više",
    "deathless-showless": "Prikaži manje",

For Serbian cyrillic:   
   "leaderboards-title": Најбољи тимови",
    "deathless-title": "Дворана славних",
    "deathless-subtitle": "Тимови који су поразили Ватреног Свињаклопа без умирања",
    "deathless-date": "Датум",
    "deathless-loading": "Учитавање...",
    "deathless-noresults": "Нема резултата.. Покушајте касније",
    "deathless-showmore": "Прикажи више",
    "deathless-showless": "Прикажи мање",

**Comment by rammba** [comment]
Hi man can u also merge addition lines for Serbian

For Serbian latin:
"leaderboards-title": "Najbolji timovi",
"deathless-title": "Dvorana slavnih",
"deathless-subtitle": "Timovi koji su porazili Vatrenog Svinjaklopa bez umiranja",
"deathless-date": "Datum",
"deathless-loading": "Učitavanje...",
"deathless-noresults": "Nema rezultata.. Pokušajte kasnije",
"deathless-showmore": "Prikaži više",
"deathless-showless": "Prikaži manje",

For Serbian cyrillic:
"leaderboards-title": Најбољи тимови",
"deathless-title": "Дворана славних",
"deathless-subtitle": "Тимови који су поразили Ватреног Свињаклопа без умирања",
"deathless-date": "Датум",
"deathless-loading": "Учитавање...",
"deathless-noresults": "Нема резултата.. Покушајте касније",
"deathless-showmore": "Прикажи више",
"deathless-showless": "Прикажи мање",

**Comment by ricardjorg** [comment]
@rammba All done! Thank you!

**Pull request closed without merging**
