### PR TITLE
Some translation corretions for Portuguese.

### PR DESCRIPTION
**Pull request by ImKyno**
"progress_lastsync": "Actualizado %1" -> "Atualizado %1"
"progress_lastsync_title": "Actualizado em %1" -> "Atualizado em %1"

"leaderboards-title": "Melhores Equipas", -> "Melhores Equipes"
"leaderboards-loading": "A obter equipas.." -> "A obter equipes..."

"leaderboards-noresults": "Nenhuns dados obtidos.. Tenta novamente", -> "Nenhum dado obtido... Tente novamente" The "Nenhuns" word doens't exist in portuguese, Changed to "Nenhum".

"localization-help": "Queres ajudar?", -> "Quer ajudar?"
 "localization-helptext": "Queres adicionar a tua língua? Envia um pull request no %1." -> "Quer adicionar a seu idioma? Envia um pull request no %1."

### CODE REVIEW

**Comment by ricardjorg** [comment]
Hi ImKynoox! Thanks for your contributions. The current Portuguese on the page is Portugal's Portuguese. I'll add your changes as Brazil's Portuguese.

**Comment by ricardjorg** [comment]
Hi again ImKynoox! Thanks again for your help. I've branched the Portuguese into the PT and BR variant. (We do use "nenhuns" in Portugal, as the plural of "nenhum"). Your changes are merged in and will go live in a few minutes. Would you like to include a link to your Klei forums profile? I included your github link for now.
Thanks again! You're awesome!

**Comment by ImKyno** [comment]
Good job! keep it up :) 
Link to my profile: https://forums.kleientertainment.com/profile/978076-kynoox_/

**Comment by ricardjorg** [comment]
@ImKynoox Updated the credits! Thanks!

**Pull request merged**
